version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "monthly"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_name: "org.apache.tinkerpop:die-dependabot"
